tofu-llama2-7b:
  hf_key: "meta-llama/llama-2-7b-chat-hf"
  question_start_tag: "[inst] "
  question_end_tag: " [/inst]"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
tofu-llama3-8b:
  hf_key: "meta-llama/meta-llama-3-8b-instruct"
  question_start_tag: "<|start_header_id|>user<|end_header_id|>\n\n"
  question_end_tag: "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
tofu-gemma-2-2b-it:
  hf_key: "google/gemma-2-2b-it"
  question_start_tag: "<start_of_turn>"
  question_end_tag: "<end_of_turn>"
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
kud-llama2-7b:
  hf_key: "meta-llama/llama-2-7b-chat-hf"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
kud-llama3-8b:
  hf_key: "meta-llama/meta-llama-3-8b-instruct"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
kud-gemma-2-2b-it:
  hf_key: "google/gemma-2-2b-it"
  question_start_tag: ""
  question_end_tag: ""
  answer_tag: ""
  flash_attention2: "false"
  gradient_checkpointing: "true"
phi:
  hf_key: "microsoft/phi-1_5"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
stablelm:
  hf_key: "stabilityai/stablelm-3b-4e1t"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
pythia-1.4:
  hf_key: "EleutherAI/pythia-1.4b-deduped"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"

